In [31]:
import pandas as pd

url = "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos/arquivos/shpc/qus/ultimas-4-semanas-gasolina-etanol.csv"

df = pd.read_csv(url, sep=';', encoding='latin1', decimal=',')

display(df)

,ï»¿Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,N,AC,RIO BRANCO,CODEPE COMBUSTIVEIS LTDA,08.220.930/0001-62,RODOVIA BR-364 (RIO BRANCO-CRUZEIRO DO SUL) - ...,2755,LOTE 01/02/03/04/05 E 33,PORTAL DA AMAZONIA,69915-630,GASOLINA,06/05/2026,7.19,NaN,R$ / litro,VIBRA
1,N,AC,RIO BRANCO,CODEPE COMBUSTIVEIS LTDA,08.220.930/0001-62,RODOVIA BR-364 (RIO BRANCO-CRUZEIRO DO SUL) - ...,2755,LOTE 01/02/03/04/05 E 33,PORTAL DA AMAZONIA,69915-630,GASOLINA ADITIVADA,06/05/2026,7.39,NaN,R$ / litro,VIBRA
2,N,AC,RIO BRANCO,CODEPE COMBUSTIVEIS LTDA,08.220.930/0001-62,RODOVIA BR-364 (RIO BRANCO-CRUZEIRO DO SUL) - ...,2755,LOTE 01/02/03/04/05 E 33,PORTAL DA AMAZONIA,69915-630,ETANOL,06/05/2026,5.19,NaN,R$ / litro,VIBRA
3,N,AC,RIO BRANCO,AUTO POSTO AMAPA LTDA,00.529.581/0001-53,VIA CHICO MENDES,3570,NaN,AREAL,69906-119,GASOLINA,06/05/2026,7.39,NaN,R$ / litro,VIBRA
4,N,AC,RIO BRANCO,AUTO POSTO AMAPA LTDA,00.529.581/0001-53,VIA CHICO MENDES,3570,NaN,AREAL,69906-119,GASOLINA ADITIVADA,06/05/2026,7.49,NaN,R$ / litro,VIBRA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45546,SE,SP,OURINHOS,AUTO POSTO BENEDETTI DE OURINHOS LTDA,60.116.243/0001-11,RUA DUQUE DE CAXIAS,1384,NaN,VILA RECREIO,19911-621,GASOLINA,28/05/2026,6.27,NaN,R$ / litro,BRANCA
45547,SE,SP,OURINHOS,AUTO POSTO BENEDETTI DE OURINHOS LTDA,60.116.243/0001-11,RUA DUQUE DE CAXIAS,1384,NaN,VILA RECREIO,19911-621,ETANOL,28/05/2026,3.34,NaN,R$ / litro,BRANCA
45548,SE,SP,MARILIA,AUTO POSTO AVENIDA ESMERALDA LTDA,06.143.204/0003-20,AVENIDA CASTRO ALVES,1856,NaN,POLON,17507-000,GASOLINA,29/05/2026,6.37,NaN,R$ / litro,IPIRANGA
45549,SE,SP,MARILIA,AUTO POSTO AVENIDA ESMERALDA LTDA,06.143.204/0003-20,AVENIDA CASTRO ALVES,1856,NaN,POLON,17507-000,GASOLINA ADITIVADA,29/05/2026,6.57,NaN,R$ / litro,IPIRANGA
45550,SE,SP,MARILIA,AUTO POSTO AVENIDA ESMERALDA LTDA,06.143.204/0003-20,AVENIDA CASTRO ALVES,1856,NaN,POLON,17507-000,ETANOL,29/05/2026,3.77,NaN,R$ / litro,IPIRANGA

In [44]:
gasolina_df = df[df["Estado - Sigla"] == "DF"]#filtra o DF

gasolina_df = gasolina_df[gasolina_df['Produto'].str.contains('GASOLINA', na=False)]#busca tudo que tem gasolina

gasolina_df['Data da Coleta'] = pd.to_datetime(gasolina_df['Data da Coleta'], format='%d/%m/%Y')#formata data

gasolina_df = gasolina_df.drop('Valor de Compra', axis=1)#apaga oq nao quero
gasolina_df = gasolina_df.drop('Complemento', axis=1)
gasolina_df = gasolina_df.dropna(subset=['Valor de Venda', 'Data da Coleta'])#remove nulos por linha

display(gasolina_df)

,ï»¿Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Unidade de Medida,Bandeira
253,CO,DF,BRASILIA,DRIVE CAR TRANSPORTES E COMBUSTIVEIS LTDA,00.012.211/0003-06,QUADRA QUADRA 1 PLL LOTE 01,S/N,SETOR INDUSTRIAL (GAMA),72445-010,GASOLINA,2026-05-05,6.09,R$ / litro,BRANCA
254,CO,DF,BRASILIA,DRIVE CAR TRANSPORTES E COMBUSTIVEIS LTDA,00.012.211/0003-06,QUADRA QUADRA 1 PLL LOTE 01,S/N,SETOR INDUSTRIAL (GAMA),72445-010,GASOLINA ADITIVADA,2026-05-05,6.09,R$ / litro,BRANCA
256,CO,DF,BRASILIA,AUTO POSTO CINCO ESTRELAS LTDA,00.692.418/0001-07,LOC SH/NORTE PLL QD 05,SN,ASA NORTE,70310-500,GASOLINA,2026-05-06,6.49,R$ / litro,VIBRA
257,CO,DF,BRASILIA,PECOBRAL COMÃRCIO DE DERIVADOS DE PETRÃLEO B...,00.689.901/0001-32,SQN-SUPERQUADRA NORTE 309 A PLL,309,ASA NORTE,70755-000,GASOLINA,2026-05-06,6.49,R$ / litro,VIBRA
258,CO,DF,BRASILIA,PECOBRAL COMÃRCIO DE DERIVADOS DE PETRÃLEO B...,00.689.901/0001-32,SQN-SUPERQUADRA NORTE 309 A PLL,309,ASA NORTE,70755-000,GASOLINA ADITIVADA,2026-05-06,6.79,R$ / litro,VIBRA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44825,CO,DF,BRASILIA,QNL POSTO DE COMBUSTIVEL LTDA,35.161.655/0001-26,QUADRA EQNL 2/4 BLOCO B,1,TAGUATINGA NORTE (TAGUATINGA),72155-502,GASOLINA ADITIVADA,2026-05-25,6.89,R$ / litro,RAIZEN
44858,CO,DF,BRASILIA,AUTO POSTO CINCO ESTRELAS LTDA,00.692.418/0026-65,QUADRA QE 2 LOTE J PLL,S/N,GUARA I,71010-003,GASOLINA,2026-05-25,6.49,R$ / litro,VIBRA
44859,CO,DF,BRASILIA,AUTO POSTO CINCO ESTRELAS LTDA,00.692.418/0026-65,QUADRA QE 2 LOTE J PLL,S/N,GUARA I,71010-003,GASOLINA ADITIVADA,2026-05-25,6.94,R$ / litro,VIBRA
45004,CO,DF,BRASILIA,POSTO DE COMBUSTIVEL AGUAS CLARAS LTDA,34.046.587/0001-91,AVENIDA PARQUE AGUAS CLARAS LOTE,625,NORTE (AGUAS CLARAS),71906-500,GASOLINA,2026-05-25,6.39,R$ / litro,VIBRA
45005,CO,DF,BRASILIA,POSTO DE COMBUSTIVEL AGUAS CLARAS LTDA,34.046.587/0001-91,AVENIDA PARQUE AGUAS CLARAS LOTE,625,NORTE (AGUAS CLARAS),71906-500,GASOLINA ADITIVADA,2026-05-25,6.69,R$ / litro,VIBRA

In [55]:

resultado_agrupado = gasolina_df.groupby("Data da Coleta")["Valor de Venda"].agg(
    Preco_Medio='mean',
    Preco_Minimo='min',
    Preco_Maximo='max',
    Qtd_Postos='count'
).reset_index() 


display(resultado_agrupado)

  Data da Coleta  Preco_Medio  Preco_Minimo  Preco_Maximo  Qtd_Postos
0     2026-05-05     6.151556          5.94          6.69          45
1     2026-05-06     6.461200          5.96          6.92          50
2     2026-05-11     6.528837          5.99          7.18          86
3     2026-05-13     6.590000          6.49          6.69           3
4     2026-05-18     6.612391          6.19          7.18          92
5     2026-05-25     6.624066          6.29          7.18          91

In [58]:
resultado_agrupado = resultado_agrupado.rename(columns={
    'Data da Coleta': 'data_coleta',
    'Preco_Medio': 'preco_medio',
    'Preco_Minimo': 'preco_minimo',
    'Preco_Maximo': 'preco_maximo',
    'Qtd_Postos': 'qtd_postos'
})

In [68]:
import sqlite3


con = sqlite3.connect("gasolina.db")
cursor = con.cursor()


cursor.execute("""
CREATE TABLE IF NOT EXISTS preco (
    data_coleta DATE PRIMARY KEY,
    preco_medio REAL,
    preco_minimo REAL,
    preco_maximo REAL,
    qtd_postos INTEGER
)
""")
con.commit()
cursor.close()


resultado_agrupado.to_sql(
    "preco",
    con,
    if_exists="append",
    index=False
)


con.close()

print("Tabela criada com tipo DATE e dados salvos com sucesso!")

IntegrityError: UNIQUE constraint failed: preco.data_coleta

           data_coleta  preco_medio  preco_minimo  preco_maximo  qtd_postos
0  2026-05-25 00:00:00     6.624066          6.29          7.18          91
1  2026-05-18 00:00:00     6.612391          6.19          7.18          92